### ISSUE TITLE
Cant use it

### ISSUE THREAD

**Issue by lachlanASF** [DragOP-Menu/DragOP-Menu#1]
Hey guys ive been trying almost all night do u think u can make a video showing everybody how to use it?

**Comment by Vertex-Client** [comment]
In case you're using Toolbox:
- Install the .js file in "Launcher Options" --> ModPEs --> import

In case you're using BlockLauncher:
- http://mcpedl.com/how-to-install-minecraft-pe-mods-for-android/

If you get any error (or if you still need help), please reply.
