### ISSUE TITLE
I can't delete it

### ISSUE THREAD

**Issue by Remlet** [DragOP-Menu/DragOP-Menu#11]
I have an Asus Zenphone Laser 2 720p or ASUS_Z00LD
when I try to delete the app the picture is too big so I can't tap the "Uninstall" button.
Can I do anything?

**Comment by Vertex-Client** [comment]
You should be able to remove it using your phone's Settings app. Open the Settings app, go to the App(lication)s section, search the app in the list, tap it and from there you should be able to remove it.

Hope this helps.
