### ISSUE TITLE
My suggestion

### ISSUE THREAD

**Issue by KoKoXeK** [DragOP-Menu/DragOP-Menu#2]
Please add ESP cheat . I play the Toolbox and although x - ray Iga overlook it would be a great replacement for your fashion search boxes fire, this mod eats little fps. and hack password (I know that the Internet can find ready-made dictionaries containing hundreds of passwords that can be downloaded ) would be an epic mod. But I do not know if it would not change the balance on server . It's just so my suggestions and I'm curious what you plan to shop for add :) I wish you all the best.

**Comment by Jaydotzip** [comment]
I think the client looks great if only I could make the button disappear
like Service hack so I could look legit

**Comment by ghost** [comment]
Todo:
-GhostMode
-Passhack

**Comment by ghost** [comment]
Passhack added.

**Comment by ghost** [comment]
Ghostmode added
