### ISSUE TITLE
Repeating task/newLevel issue

### ISSUE THREAD

**Issue by Vertex-Client** [DragOP-Menu/DragOP-Menu#3]
**The issue**
The bug I'm talking about is this: when closing a module's screen/dialog, the repeating task will automatically detect that there is no GUI and will set isRemote to true and call levelFakeCallback, but this causes a newLevel call for every mod, this could make the game lag, so it would be great if we fixed it asap.

**How to reproduce**
1. Install a random mod that sends messages in newLevel + DragOP.
2. Open a mod's screen/dialog
3. Close it.
4. Now you will most probably a message showing up (the message that was shown in newLevel).

**Comment by ghost** [comment]
Do we still need the Blocklauncher Server workaround?

**Comment by Vertex-Client** [comment]
There's another workaround (check for the server's ip). That one even works without GUI.

**Comment by ghost** [comment]
I think this can be closed because i removed the Blocklauncher Server workaround
