### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [DragOP-Menu/DragOP-Menu#4]
The client Godsoft made (ServiceHack) had passhack, please add it to DragOP,, because of its broken in servicehack and I like DragOP alot better!

**Comment by ghost** [comment]
I´ll see if i can add it.

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
NP

**Comment by ghost** [comment]
Added.

**Comment by Affannnn** [comment]
lol why won't u try to fix service hack?!

**Comment by Vertex-Client** [comment]
Because he stopped working on ServiceHack, DragOP can be seen as the sequal to ServiceHack.

**Comment by ghost** [comment]
And I cannot understand why you guys are commenting a added suggestion... LOL

**Comment by Vertex-Client** [comment]
I replied to his comment, because he had a question.

**Comment by ghost** [comment]
Ok you answered but i wonder why he asks in a closed issue

**Comment by Vertex-Client** [comment]
We didn't close this issue's conversation yet, I think I will do that now.
