### ISSUE TITLE
Add KillAura

### ISSUE THREAD

**Issue by officalcalebdaix** [DragOP-Menu/DragOP-Menu#6]
Please add KillAura and make it work on servers. Also I love DragOP and I use it in my hacking videos. Really hope you add KillAura.

**Comment by officalcalebdaix** [comment]
https://www.youtube.com/channel/UCv1kHYRWNwZJxYZM31m8z2A

**Comment by ghost** [comment]
Unfortunately this is not possible for us at the moment.
