### ISSUE TITLE
Phase Error

### ISSUE THREAD

**Issue by Affannnn** [DragOP-Menu/DragOP-Menu#7]
I Tried To Use Dev Version But It Shows Error Please Fix It!

**Comment by ghost** [comment]
Please provide more info about the issue

**Comment by Affannnn** [comment]
The error is big and I Am On V3 Beta Script Loader

**Comment by ghost** [comment]
Do you use the latest toolbox beta?

**Comment by Affannnn** [comment]
I Don't Have Beta I Have Latest Bug Fix Of Toolbox Which Released

**Comment by ghost** [comment]
Try the latest dev version

**Comment by Affannnn** [comment]
Ok

**Comment by Affannnn** [comment]
Thanks For The Fix! :-)
