### ISSUE TITLE
cant login into servers

### ISSUE THREAD

**Issue by shadmarc** [DragOP-Menu/DragOP-Menu#9]
Hello godsoft I love your client but i can't log into specific servers because the servers have replaced the / with a . before command and because of that dragop acts like I would like to run a command (the server on the screenshot is mineplex)
I suggest adding a switch to enable/disable the dragop commands :)
Mcpe version: 0.16.0.5
Launcher: toolbox
Device: lenovo A-7600

![screenshot_2016-11-03-00-31-23](https://cloud.githubusercontent.com/assets/23214214/19949887/f487972e-a15c-11e6-9057-d8575317ad91.png)

**Comment by ghost** [comment]
Will be fixed in the next days

**Comment by shadmarc** [comment]
Awesome :D

**Comment by shadmarc** [comment]
I fixed it already  by changing the "." To "@" may I send you this version?
![screenshot_2016-11-03-22-02-55](https://cloud.githubusercontent.com/assets/23214214/19983192/aa390ef4-a211-11e6-90ba-3b7be6dfecdb.png)

**Comment by ghost** [comment]
You must not send it. There will be settings to change the command prefix and disable commands fully

**Comment by shadmarc** [comment]
Oh ok nice :)

**Comment by ghost** [comment]
This should be fixed now.
